# Generated by Django 5.1.5 on 2025-01-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_post_creator_remove_comment_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
