# Generated by Django 5.1.5 on 2025-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('category', models.CharField(max_length=20, verbose_name='종류')),
                ('explanation', models.TextField(verbose_name='설명')),
            ],
        ),
    ]
