# Generated by Django 5.1.4 on 2025-01-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('releasedAt', models.IntegerField()),
                ('genre', models.TextField()),
                ('stars', models.IntegerField()),
                ('runningTime', models.IntegerField()),
                ('comments', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
            ],
        ),
    ]
