# Generated by Django 5.1.4 on 2025-01-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releasedAt',
            new_name='releasedYear',
        ),
    ]
