# Generated by Django 5.1.4 on 2025-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_releasedat_movie_releasedyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.TextField(),
        ),
    ]
