# Generated by Django 5.1.4 on 2025-01-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_movie_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posterURL',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
