# Generated by Django 5.1.4 on 2025-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_posterurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posterURL',
            field=models.TextField(default='https://i.namu.wiki/i/BIl3oY17WExT8MRfFK8BAd_OrbuAe6dbY4ouievj5wKjZN5vZqeYF0oGRo37UEnqmRAr4cOxer2xVR7VoMAvgw.webp'),
        ),
    ]
