# Generated by Django 5.1.5 on 2025-01-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DevTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='아이디어 이름')),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y%m%d', verbose_name='사진')),
                ('explanation', models.TextField(verbose_name='설명')),
                ('interest', models.IntegerField(verbose_name='관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('expectedTool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevTool.devtool', verbose_name='개발툴')),
            ],
        ),
    ]
