# Generated by Django 5.1.5 on 2025-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.BooleanField(default=False, verbose_name='찜 여부'),
        ),
    ]
